-- ============================================================
-- Seed: 128 francobolli Repubblica Italiana (1996–2025)
-- Eseguire DOPO schema.sql, se la tabella è vuota.
-- ============================================================

INSERT INTO stamps
  (title, subtitle, anno, valore, serie, sassone, dentellatura, carta, colore, era, posseduto, condizione, priorita, immagine, note)
VALUES
  ('Fondazione di Roma', '2750° anniversario', 1996, '750 L', 'Commemorativa', 'Sa. 2215', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Donne famose', 'Grazia Deledda', 1996, '750 L', 'Europa CEPT', 'Sa. 2218', '14x13½', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Atlanta', 'Centesima edizione dei Giochi Olimpici', 1996, '750 L', 'Sport', 'Sa. 2221', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Giorgio Morandi', 'Centenario della nascita', 1996, '750 L', 'Arte italiana', 'Sa. 2225', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('UNICEF — 50° anniversario', 'Fondo ONU per l''infanzia', 1996, '750 L', 'Anniversari', 'Sa. 2228', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Amalfi', 'Serie turistica', 1996, '750 L', 'Turismo', 'Sa. 2230', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Ferrara', 'Serie turistica', 1996, '750 L', 'Turismo', 'Sa. 2231', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Francesco Petrarca', '700° anniversario della nascita', 1997, '800 L', 'Anniversari', 'Sa. 2245', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Storie e leggende', 'Serie Europa CEPT 1997', 1997, '800 L', 'Europa CEPT', 'Sa. 2248', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Trattati di Roma — 40° anniversario', 'Fondazione della CEE', 1997, '800 L', 'Europa', 'Sa. 2252', '14', 'Patinata', 'Blu e oro', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Antonio Gramsci', '60° anniversario della morte', 1997, '800 L', 'Personaggi illustri', 'Sa. 2255', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Costiera Amalfitana', 'Siti italiani UNESCO', 1997, '800 L', 'Patrimonio UNESCO', 'Sa. 2259', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Campionati Mondiali di Sci — Sestriere', 'Mondiali di sci alpino 1997', 1997, '800 L', 'Sport', 'Sa. 2262', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Festival nazionali', 'Serie Europa CEPT 1998', 1998, '800 L', 'Europa CEPT', 'Sa. 2278', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali di calcio Francia ''98', 'XVI Coppa del Mondo FIFA', 1998, '800 L', 'Sport', 'Sa. 2281', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Enzo Ferrari', 'Centenario della nascita', 1998, '800 L', 'Personaggi illustri', 'Sa. 2285', '14', 'Patinata', 'Rosso e nero', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Luigi Einaudi', 'Presidente della Repubblica', 1998, '800 L', 'Personaggi illustri', 'Sa. 2288', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Pompei', 'Siti italiani UNESCO', 1998, '800 L', 'Patrimonio UNESCO', 'Sa. 2291', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Parchi naturali', 'Serie Europa CEPT 1999', 1999, '800 L', 'Europa CEPT', 'Sa. 2305', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Venezia', 'Serie turistica', 1999, '800 L', 'Turismo', 'Sa. 2308', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Vincenzo Bellini', 'Bicentenario della nascita', 1999, '800 L', 'Musica italiana', 'Sa. 2311', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Anno Internazionale degli Anziani', 'ONU', 1999, '800 L', 'Anniversari', 'Sa. 2314', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Giubileo 2000 — Porta Santa', 'Anno Santo', 2000, '800 L', 'Giubileo', 'Sa. 2325', '14', 'Patinata', 'Oro e multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa 2000', 'Serie Europa CEPT', 2000, '800 L', 'Europa CEPT', 'Sa. 2328', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Bimillenario di Virgilio', '2000° anniversario della morte', 2000, '800 L', 'Cultura italiana', 'Sa. 2331', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Sydney', 'XXVII Giochi Olimpici', 2000, '800 L', 'Sport', 'Sa. 2334', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Moda', 'Eccellenze italiane', 2000, '800 L', 'Made in Italy', 'Sa. 2337', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Cinque Terre', 'Siti italiani UNESCO', 2000, '800 L', 'Patrimonio UNESCO', 'Sa. 2340', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Acqua, ricchezza naturale', 'Serie Europa CEPT 2001', 2001, '800 L', 'Europa CEPT', 'Sa. 2355', '14', 'Patinata', 'Azzurro e verde', 'repubblica', true, 'fds', NULL, NULL, 'Ultimo anno delle emissioni in Lire'),
  ('Turismo — Agrigento', 'Serie turistica', 2001, '800 L', 'Turismo', 'Sa. 2358', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Introduzione dell''Euro', 'Nuova moneta europea', 2002, '0,41 €', 'Commemorativa', 'Sa. 2370', '14', 'Patinata', 'Oro e blu', 'repubblica', true, 'fds', NULL, NULL, 'Prima emissione in Euro'),
  ('Europa — Il circo', 'Serie Europa CEPT 2002', 2002, '0,41 €', 'Europa CEPT', 'Sa. 2373', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2002', 'Corea-Giappone', 2002, '0,41 €', 'Sport', 'Sa. 2376', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Design', 'Eccellenze italiane', 2002, '0,62 €', 'Made in Italy', 'Sa. 2379', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Federico Fellini', 'Regista cinematografico', 2003, '0,41 €', 'Cinema italiano', 'Sa. 2390', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Arte del poster', 'Serie Europa CEPT 2003', 2003, '0,41 €', 'Europa CEPT', 'Sa. 2393', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Carabinieri — 189° anniversario', 'Arma dei Carabinieri', 2003, '0,41 €', 'Forze Armate', 'Sa. 2396', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Val di Noto', 'Siti italiani UNESCO', 2003, '0,62 €', 'Patrimonio UNESCO', 'Sa. 2399', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Matera', 'Serie turistica', 2003, '0,41 €', 'Turismo', 'Sa. 2402', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Vacanze', 'Serie Europa CEPT 2004', 2004, '0,45 €', 'Europa CEPT', 'Sa. 2415', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Atene 2004', 'XXVIII Giochi Olimpici', 2004, '0,45 €', 'Sport', 'Sa. 2418', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Alimentare', 'Eccellenze italiane', 2004, '0,45 €', 'Made in Italy', 'Sa. 2421', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Leonardo da Vinci — Uomo Vitruviano', 'Arte rinascimentale', 2004, '0,62 €', 'Arte italiana', 'Sa. 2424', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Rotary International — 100° anniversario', 'Centenario fondazione', 2005, '0,45 €', 'Anniversari', 'Sa. 2435', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Gastronomia', 'Serie Europa CEPT 2005', 2005, '0,45 €', 'Europa CEPT', 'Sa. 2438', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Giochi Olimpici Invernali — Torino 2006', 'XX Olimpiade invernale', 2005, '0,45 €', 'Sport', 'Sa. 2441', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Palermo', 'Serie turistica', 2005, '0,45 €', 'Turismo', 'Sa. 2444', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi Invernali Torino 2006', 'XX Giochi Olimpici Invernali', 2006, '0,45 €', 'Sport', 'Sa. 2455', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Integrazione', 'Serie Europa CEPT 2006', 2006, '0,45 €', 'Europa CEPT', 'Sa. 2458', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2006 — Campioni del Mondo', 'Germania 2006', 2006, '0,60 €', 'Sport', 'Sa. 2462', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, 'L''Italia vince il Mondiale'),
  ('Patrimonio UNESCO — Genova', 'Siti italiani UNESCO', 2006, '0,60 €', 'Patrimonio UNESCO', 'Sa. 2465', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Scoutismo', 'Serie Europa CEPT 2007', 2007, '0,60 €', 'Europa CEPT', 'Sa. 2478', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Trattati di Roma — 50° anniversario', 'Unione Europea', 2007, '0,60 €', 'Europa', 'Sa. 2481', '14', 'Patinata', 'Blu e oro', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Moto', 'Eccellenze italiane', 2007, '0,60 €', 'Made in Italy', 'Sa. 2484', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Bari', 'Serie turistica', 2007, '0,60 €', 'Turismo', 'Sa. 2487', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — La lettera', 'Serie Europa CEPT 2008', 2008, '0,60 €', 'Europa CEPT', 'Sa. 2498', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Pechino 2008', 'XXIX Giochi Olimpici', 2008, '0,60 €', 'Sport', 'Sa. 2501', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Campionato Europeo di Calcio Euro 2008', 'Austria-Svizzera', 2008, '0,60 €', 'Sport', 'Sa. 2504', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Isole Eolie', 'Siti italiani UNESCO', 2008, '0,60 €', 'Patrimonio UNESCO', 'Sa. 2507', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Astronomia', 'Anno Internazionale dell''Astronomia', 2009, '0,65 €', 'Europa CEPT', 'Sa. 2518', '14', 'Patinata', 'Blu e multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Galileo Galilei', 'Anno Internazionale dell''Astronomia', 2009, '0,65 €', 'Scienza italiana', 'Sa. 2521', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Verona', 'Serie turistica', 2009, '0,65 €', 'Turismo', 'Sa. 2524', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Charles Darwin — 200° anniversario', 'Bicentenario della nascita', 2009, '0,65 €', 'Anniversari', 'Sa. 2527', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Libri per bambini', 'Serie Europa CEPT 2010', 2010, '0,65 €', 'Europa CEPT', 'Sa. 2538', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('150° Unità d''Italia — preparazione', 'Verso il centocinquantenario', 2010, '0,65 €', 'Anniversari', 'Sa. 2541', '14', 'Patinata', 'Verde e rosso', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2010 — Sudafrica', 'XIX Coppa del Mondo FIFA', 2010, '0,65 €', 'Sport', 'Sa. 2544', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Cantieristica navale', 'Eccellenze italiane', 2010, '0,65 €', 'Made in Italy', 'Sa. 2547', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('150° Unità d''Italia', 'Centocinquantenario', 2011, '0,60 €', 'Anniversari', 'Sa. 3245', '14', 'Patinata', 'Tricolore', 'repubblica', true, 'fds', NULL, NULL, 'Emissione celebrativa principale'),
  ('Europa — Boschi', 'Serie Europa CEPT 2011', 2011, '0,60 €', 'Europa CEPT', 'Sa. 3248', '14', 'Patinata', 'Verde e multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Monte San Giorgio', 'Siti italiani UNESCO', 2011, '0,60 €', 'Patrimonio UNESCO', 'Sa. 3251', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Napoli', 'Serie turistica', 2011, '0,60 €', 'Turismo', 'Sa. 3254', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Visita', 'Serie Europa CEPT 2012', 2012, '0,60 €', 'Europa CEPT', 'Sa. 3265', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Londra 2012', 'XXX Giochi Olimpici', 2012, '0,60 €', 'Sport', 'Sa. 3268', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Orafi', 'Eccellenze italiane', 2012, '0,60 €', 'Made in Italy', 'Sa. 3271', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Euro 2012 — Campionato Europeo', 'Polonia e Ucraina', 2012, '0,60 €', 'Sport', 'Sa. 3274', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Veicoli postali', 'Serie Europa CEPT 2013', 2013, '0,70 €', 'Europa CEPT', 'Sa. 3285', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Firenze', 'Serie turistica', 2013, '0,70 €', 'Turismo', 'Sa. 3288', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Longobardi', 'Siti italiani UNESCO', 2013, '0,70 €', 'Patrimonio UNESCO', 'Sa. 3291', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('200° anniversario dei Carabinieri', 'Bicentenario fondazione', 2014, '0,70 €', 'Forze Armate', 'Sa. 3302', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Strumenti musicali', 'Serie Europa CEPT 2014', 2014, '0,70 €', 'Europa CEPT', 'Sa. 3305', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2014 — Brasile', 'XX Coppa del Mondo FIFA', 2014, '0,70 €', 'Sport', 'Sa. 3308', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Robotica', 'Eccellenze italiane', 2014, '0,70 €', 'Made in Italy', 'Sa. 3311', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Giocattoli antichi', 'Serie Europa CEPT 2015', 2015, '0,80 €', 'Europa CEPT', 'Sa. 3322', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('EXPO 2015 Milano', 'Nutrire il Pianeta', 2015, '0,80 €', 'Esposizioni universali', 'Sa. 3325', '14', 'Patinata', 'Verde e multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Roma', 'Serie turistica', 2015, '0,80 €', 'Turismo', 'Sa. 3328', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Etna', 'Siti italiani UNESCO', 2015, '0,80 €', 'Patrimonio UNESCO', 'Sa. 3331', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Think Green', 'Serie Europa CEPT 2016', 2016, '0,95 €', 'Europa CEPT', 'Sa. 3342', '14', 'Patinata', 'Verde e bianco', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Rio 2016', 'XXXI Giochi Olimpici', 2016, '0,95 €', 'Sport', 'Sa. 3345', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Euro 2016 — Campionato Europeo', 'Francia', 2016, '0,95 €', 'Sport', 'Sa. 3348', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Cinema', 'Eccellenze italiane', 2016, '0,95 €', 'Made in Italy', 'Sa. 3351', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Castelli', 'Serie Europa CEPT 2017', 2017, '0,95 €', 'Europa CEPT', 'Sa. 3362', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Palermo arabo-normanna', 'Siti italiani UNESCO', 2017, '0,95 €', 'Patrimonio UNESCO', 'Sa. 3365', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Milano', 'Serie turistica', 2017, '0,95 €', 'Turismo', 'Sa. 3368', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Ponti', 'Serie Europa CEPT 2018', 2018, '1,00 €', 'Europa CEPT', 'Sa. 3379', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2018 — Russia', 'XXI Coppa del Mondo FIFA', 2018, '1,00 €', 'Sport', 'Sa. 3382', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Aeronautica', 'Eccellenze italiane', 2018, '1,00 €', 'Made in Italy', 'Sa. 3385', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Colosseo', 'Siti italiani UNESCO', 2018, '1,00 €', 'Patrimonio UNESCO', 'Sa. 3388', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Giochi nazionali', 'Serie Europa CEPT 2019', 2019, '1,10 €', 'Europa CEPT', 'Sa. 3399', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Lecce', 'Serie turistica', 2019, '1,10 €', 'Turismo', 'Sa. 3402', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Leonardo da Vinci — 500° anniversario', 'Cinquecentenario della morte', 2019, '1,10 €', 'Arte italiana', 'Sa. 3405', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Raffaello Sanzio — 500° anniversario', 'Cinquecentenario della morte', 2020, '1,10 €', 'Arte italiana', 'Sa. 3416', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Vie antiche', 'Serie Europa CEPT 2020', 2020, '1,10 €', 'Europa CEPT', 'Sa. 3419', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Operatori Sanitari — COVID-19', 'Omaggio ai sanitari italiani', 2020, '1,10 €', 'Commemorativa', 'Sa. 3422', '14', 'Patinata', 'Bianco e rosso', 'repubblica', true, 'fds', NULL, NULL, 'Emissione speciale durante la pandemia'),
  ('Turismo — Trieste', 'Serie turistica', 2020, '1,10 €', 'Turismo', 'Sa. 3425', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Farmaceutica', 'Eccellenze italiane', 2020, '1,10 €', 'Made in Italy', 'Sa. 3428', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Tokyo 2020', 'XXXII Giochi Olimpici', 2021, '1,10 €', 'Sport', 'Sa. 3439', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, 'Disputate nel 2021 causa pandemia'),
  ('Europa — Animali in via di estinzione', 'Serie Europa CEPT 2021', 2021, '1,10 €', 'Europa CEPT', 'Sa. 3442', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Dante Alighieri — 700° anniversario', 'Settimo centenario della morte', 2021, '1,10 €', 'Cultura italiana', 'Sa. 3445', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Euro 2020 — Campionato Europeo', 'Vince l''Italia!', 2021, '1,10 €', 'Sport', 'Sa. 3448', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, 'L''Italia vince il campionato europeo 2020'),
  ('Turismo — Torino', 'Serie turistica', 2021, '1,10 €', 'Turismo', 'Sa. 3451', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Storie e miti', 'Serie Europa CEPT 2022', 2022, '1,20 €', 'Europa CEPT', 'Sa. 3462', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi Invernali Pechino 2022', 'XXIV Giochi Olimpici Invernali', 2022, '1,20 €', 'Sport', 'Sa. 3465', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Lusso', 'Eccellenze italiane', 2022, '1,20 €', 'Made in Italy', 'Sa. 3468', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Mondiali FIFA 2022 — Qatar', 'XXII Coppa del Mondo FIFA', 2022, '1,20 €', 'Sport', 'Sa. 3471', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Siena', 'Siti italiani UNESCO', 2022, '1,20 €', 'Patrimonio UNESCO', 'Sa. 3474', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Bologna', 'Serie turistica', 2022, '1,20 €', 'Turismo', 'Sa. 3477', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Pace, il valore più prezioso', 'Serie Europa CEPT 2023', 2023, '1,25 €', 'Europa CEPT', 'Sa. 3488', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Giorgia Meloni — Presidente del Consiglio', 'Prima Presidente del Consiglio donna', 2023, '1,25 €', 'Personaggi', 'Sa. 3491', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Tecnologia', 'Eccellenze italiane', 2023, '1,25 €', 'Made in Italy', 'Sa. 3494', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Genova', 'Serie turistica', 2023, '1,25 €', 'Turismo', 'Sa. 3497', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Patrimonio UNESCO — Assisi', 'Siti italiani UNESCO', 2023, '1,25 €', 'Patrimonio UNESCO', 'Sa. 3500', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Fauna e flora sottomarina', 'Serie Europa CEPT 2024', 2024, '1,30 €', 'Europa CEPT', 'Sa. 3511', '14', 'Patinata', 'Blu e multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Olimpiadi di Parigi 2024', 'XXXIII Giochi Olimpici', 2024, '1,30 €', 'Sport', 'Sa. 3514', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Euro 2024 — Campionato Europeo', 'Germania', 2024, '1,30 €', 'Sport', 'Sa. 3517', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Made in Italy — Artigianato', 'Eccellenze italiane', 2024, '1,30 €', 'Made in Italy', 'Sa. 3520', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo — Palermo', 'Serie turistica', 2024, '1,30 €', 'Turismo', 'Sa. 3523', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Europa — Tradizioni e folclore', 'Serie Europa CEPT 2025', 2025, '1,35 €', 'Europa CEPT', 'Sa. —', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, NULL),
  ('Turismo 2025', 'Serie turistica', 2025, '1,35 €', 'Turismo', 'Sa. —', '14', 'Patinata', 'Multicolore', 'repubblica', true, 'fds', NULL, NULL, 'Emissione in corso d''anno');
